apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: nodejs-app
    namespace: argocd
  spec:
    destination:
      namespace: dev
      server: https://kubernetes.default.svc
    project: default
    source:
      path: helm/node
      repoURL: https://github.com/vijaykumar-01/Node.js-app.git
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: nodejs-app
    namespace: dev
- apiVersion: v1
  kind: Service
  metadata:
    name: nodejs-app
    namespace: dev
  spec:
    selector:
      app: nodejs-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nodejs-app
    namespace: dev
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nodejs-app
    template:
      metadata:
        labels:
          app: nodejs-app
      spec:
        containers:
        - name: nodejs-app
          image: vijatykumar1/node-app:v8-ci
          ports:
          - containerPort: 3000
